version: 0.2
phases:
  install:
    commands:
      - curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
      - yum install -y nodejs
      - node --version
  build:
    commands:
      - npm ci
      - npm run build
artifacts:
  files:
    - '**/*'
  exclude-paths:
    - .git/**